# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jaz
email: jazsakr@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# thumbnail for website
teaser: /assets/images/igv-snapshot-thumbnail-2025-06-02.png

# add logo to navigation menu
masthead_title: "Home"
logo: "/assets/images/house_icon_from_font_awesome.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/

paginate: 7 # amount of posts to show
paginate_path: /recent/page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Reading files
include:
  - _pages
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

enable_copy_code_button: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name   : "Jaz Sakr"
  avatar : "/assets/images/igv-snapshot-thumbnail-2025-06-02.png"
#  bio    : "jazsakr@gmail.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jazsakr.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jazsakr"
    - label: "ORCiD"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0000-0002-4470-3192"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/jaz_sakr"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jazsakr"
    - label: "ORCiD"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0000-0002-4470-3192"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/jaz_sakr"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
  # _website
  - scope:
      path: ""
      type: website
    values:
      layout: single
      author_profile: true
      share: true

# Collections
collections:
  website:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-NT051ZH671"
    anonymize_ip: true 
